### ISSUE TITLE
Unable to Connect to LDAP

### ISSUE THREAD

**Issue by Nicholas-Hoff** [etianen/django-python3-ldap#105]
Great job on this project and glad to see your active.  I'm having issue getting django-python3-ldap to work correctly.  

Below is my settings.py

```
# Application definition

INSTALLED_APPS = [
    'django_python3_ldap',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
]


AUTHENTICATION_BACKENDS = (
    'django_python3_ldap.auth.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# The URL of the LDAP server.
LDAP_AUTH_URL = "ldap://159.139.152.114:389"


# Initiate TLS on connection.
LDAP_AUTH_USE_TLS = False

# The LDAP search base for looking up users.
LDAP_AUTH_SEARCH_BASE = "DC=hca,DC=corpad,DC=net"

LDAP_AUTH_OBJECT_CLASS = "cn"

# User model fields mapped to the LDAP
# attributes that represent them.
LDAP_AUTH_USER_FIELDS = {
    "user": "sAMAccountName",
    "first_name": "givenName",
    "email": "userPrincipalName",
    "usercoid":"extensionAttribute10"
}

# A tuple of django model fields used to uniquely identify a user.
LDAP_AUTH_USER_LOOKUP_FIELDS = ("userid",)

# Path to a callable that takes a dict of {model_field_name: value},
# returning a dict of clean model data.
# Use this to customize how data loaded from LDAP is saved to the User model.
LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

# Path to a callable that takes a user model and a dict of {ldap_field_name: [value]},
# and saves any additional user relationships based on the LDAP data.
# Use this to customize how data loaded from LDAP is saved to User model relations.
# For customizing non-related User model fields, use LDAP_AUTH_CLEAN_USER_DATA.
LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

# Path to a callable that takes a dict of {ldap_field_name: value},
# returning a list of [ldap_search_filter]. The search filters will then be AND'd
# together when creating the final search filter.
LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

# Path to a callable that takes a dict of {model_field_name: value}, and returns
# a string of the username to bind to the LDAP server.
# Use this to support different types of LDAP server.
LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

# Sets the login domain for Active Directory users.
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "hca.corpad.net"

# The LDAP username and password of a user for querying the LDAP database for user
# details. If None, then the authenticated user will be used for querying, and
# the `ldap_sync_users` command will perform an anonymous query.
# I also tried with None.
LDAP_AUTH_CONNECTION_USERNAME = "Domain\\User"
LDAP_AUTH_CONNECTION_PASSWORD = "Password)"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["file"],
            "level": "INFO",
        },
    },
}

MIDDLEWARE = [

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'security.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'security.wsgi.application'
```

I've attempted to run python manage.py ldap_sync_user but I'm greeted with the following error, when using HCA\\UserName and my Network password:

```
PS C:\python\security> python manage.py ldap_sync_users
CommandError: Could not connect to LDAP server
```

If I try to use None for User and Password i'm greeted with the following:
```
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPOperationsErrorResult: LDAPOperationsErrorResult - 1 - operationsError - None - 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed o
n the connection., data 0, v2580  - searchResDone - None
```
When I review my logging file it shows I'm connecting and binding when I run my application:

```
LDAP connect succeeded
LDAP connect succeeded
LDAP connect succeeded
LDAP connect succeeded
LDAP connect succeeded
LDAP connect succeeded
LDAP connect succeeded
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect succeeded
LDAP connect succeeded
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect succeeded
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect succeeded
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect succeeded
LDAP connect succeeded
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None
LDAP connect succeeded
```

However, when I look at my Django application it will show the current user logged in as anon and using a username and network password isn't working correctly.  Please help.

**Comment by etianen** [comment]
Let's fix the ldap_sync_users first. What is showing up in the logs?

**Comment by Nicholas-Hoff** [comment]
Nothing is showing up in the log for the manage.py ldap_sync_users command.  All I receive is CommandError: Could not connect to LDAP server.

**Comment by etianen** [comment]
I'm not sure that's possible. Looking at the codebase, I can't see how the
connection can fail without logging something.

https://github.com/etianen/django-python3-ldap/blob/master/django_python3_ldap/ldap.py#L121

**Comment by Nicholas-Hoff** [comment]
I deleted the log and ran python manage.py ldap_sync_users with  

LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None

and it gives me the following:

```
PS C:\python\security> python manage.py ldap_sync_users
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django_python3_ldap\management\commands\ldap_sync_users.py", line 24, in handle
    for user in connection.iter_users():
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\django_python3_ldap\ldap.py", line 93, in <genexpr>
    self._get_or_create_user(entry)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\ldap3\extend\standard\PagedSearch.py", line 63, in paged_search_generator
    None if cookie is True else cookie)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\ldap3\core\connection.py", line 765, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\ldap3\strategy\sync.py", line 142, in post_send_search
    responses, result = self.get_response(message_id)
  File "C:\Users\HFA9592\AppData\Local\Programs\Python\Python36\lib\site-packages\ldap3\strategy\base.py", line 379, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPOperationsErrorResult: LDAPOperationsErrorResult - 1 - operationsError - None - 000004DC: LdapErr: DSID-0C0907C2, comment: In order to perform this operation a successful bind must be completed o
n the connection., data 0, v2580  - searchResDone - None
```

However, when I look at what the log wrote it states LDAP connect succeeded.

If I put in my credentials and run 

PS C:\python\security> python manage.py ldap_sync_us

It gives me the following:

CommandError: Could not connect to LDAP server

The debug.log file has the line: 

`LDAP connect failed: LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580  - bindResponse - None`

Nothing else is being wrote to the log file.

**Comment by Nicholas-Hoff** [comment]
As a side note, I spoke with my system admin and he stated our auth_active_directory_domain is just "HCA", so I changed that and it appears the manage.py ldap_sync user command runs, writes connection successful to the logfile, but it's not writing to my user model.

**Comment by etianen** [comment]
So ./manage.py ldap_sync_users no exits without error, but doesn't create
any users?

I suspect that your LDAP_AUTH_SEARCH_BASE or LDAP_AUTH_OBJECT_CLASS is
incorrect.

**Comment by Nicholas-Hoff** [comment]
I queried my LDAP server and both LDAP_AUTH_SEARCH_BASE and LDAP_AUTH_OBJECT_CLASS is correct, the search base is at the lowest level though since users are assigned at different OU's based on the facility they are in.  Below are my results from the LDAP server, cn is the unique ID that identifies a user, i removed the other information for security purposes:

`ldap_search_s(ld, "CN=HFA9592,OU=U08732,OU=08732,DC=hca,DC=corpad,DC=net", 2, "(objectClass=*)", attrList,  0, &msg)
Getting 1 entries:
Dn: CN=HFA9592,OU=U08732,OU=08732,DC=hca,DC=corpad,DC=net
cn: HFA9592; 
`

**Comment by etianen** [comment]
In your settings you pasted earlier, you said:

LDAP_AUTH_OBJECT_CLASS = "cn"

Yes in your query, you're using objectClass=*

So might it not be the object class is incorrect? cn is not a normal object
class.

**Comment by Nicholas-Hoff** [comment]
The query was to pull in all fields.  cn is an object class for employee ID's.  Here is the refined query only pulling in cn:

```
***Searching...
ldap_search_s(ld, "CN=HFA9592,OU=U08732,OU=08732,DC=hca,DC=corpad,DC=net", 2, "(objectClass=*)", attrList,  0, &msg)
Getting 1 entries:
Dn: CN=HFA9592,OU=U08732,OU=08732,DC=hca,DC=corpad,DC=net
cn: HFA9592; 
```

**Comment by Nicholas-Hoff** [comment]
Dave, 
Turns out I had to use objectClass = user instead of cn as you suggested.  Thanks for helping me figure this out and I appreciate the work you've put into this project!

**Comment by etianen** [comment]
No worries. LDAP is far too complicated, IMO. :)
