### ISSUE TITLE
Running ldap_sync_users returns KeyError: 'username' 

### ISSUE THREAD

**Issue by dev-nullified** [etianen/django-python3-ldap#112]
I'm having an error with the 'ldap_sync_users' command where it returns `` KeyError: 'username' ``

**Environment:**
django ver: 1.11.9
OS: Debian GNU/Linux 8 (jessie)
LDAP backend: Active Directory

**Here is the error from the console:**
```Python traceback
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 21, in handle
    with ldap.connection(**auth_kwargs) as connection:
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 140, in connection
    username = format_username(kwargs)
  File "/usr/local/lib/python3.6/site-packages/django_python3_ldap/utils.py", line 88, in format_username_active_directory
    username = model_fields["username"]
KeyError: 'username'
```

**LDAP config:**
```Python
LDAP_AUTH_URL = "ldap://corp.contoso.com:389"

LDAP_AUTH_USE_TLS = False

LDAP_AUTH_SEARCH_BASE = "ou=contoso users,dc=corp,dc=contoso,dc=com"

LDAP_AUTH_OBJECT_CLASS = "sAMAccountName"

LDAP_AUTH_USER_FIELDS = {
    "first_name": "givenName",
    "last_name": "sn",
    "middle_initial" : "initials",
    "email": "mail",
    "Office": "physicalDeliveryOfficeName",
    "Title": "title",
    "Department": "department",
    "manager": "manager",
}

LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

LDAP_AUTH_CLEAN_USER_DATA = "django_python3_ldap.utils.clean_user_data"

LDAP_AUTH_SYNC_USER_RELATIONS = "django_python3_ldap.utils.sync_user_relations"

LDAP_AUTH_FORMAT_SEARCH_FILTERS = "django_python3_ldap.utils.format_search_filters"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory"

LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = 'CORP'

LDAP_AUTH_CONNECTION_USERNAME = 'contosoAdmin'
LDAP_AUTH_CONNECTION_PASSWORD = 'somepassword'

LDAP_AUTH_CONNECT_TIMEOUT = None
LDAP_AUTH_RECEIVE_TIMEOUT = None

```

**Comment by etianen** [comment]
Your LDAP_AUTH_USER_FIELDS setting should be a mapping of user model field
names to LDAP field names.

In your LDAP_AUTH_USER_LOOKUP_FIELDS setting, you specify that
`User.username` is a unique field for lookup. But LDAP_AUTH_USER_FIELDS is
missing a `username` key.

Does your user model have a `username` field? If so, you need to map it to
an LDAP field in LDAP_AUTH_USER_FIELDS. If not, you need to change
LDAP_AUTH_USER_FIELDS to reference a unique field on your user model.

**Comment by dev-nullified** [comment]
Whoops, that's my bad. I'm using email as the unique filed in my user model. 

I've made the changes as suggested
```Python
LDAP_AUTH_USER_LOOKUP_FIELDS = ("email",)
```
However, I still get the exact same error above when rerunning 'ldap_sync_users'.

**Comment by etianen** [comment]
Looks like you're also going to have to make a custom
LDAP_AUTH_FORMAT_USERNAME implementation.

Active directory typically expects a username in the form
"domain\\username" or "username@domain". Since your user model does not
have a username, none of these really makes sense.

What format does your server expect usernames in for bind()?
