### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'receive_timeout'

### ISSUE THREAD

**Issue by JAusm** [etianen/django-python3-ldap#119]
Hello,

I am using django-python3-ldap version 0.11.1 and python3-ldap version 0.9.8.4. I am getting an error when I try to run ldap_sync_users:

My settings look correct. Do you know why I would receive this error?

**Comment by JAusm** [comment]
Trace:
`Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 21, in handle
    with ldap.connection(**auth_kwargs) as connection:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/Envs/qa_reporting_suite/lib/python3.5/site-packages/django_python3_ldap/ldap.py", line 159, in connection
    receive_timeout=settings.LDAP_AUTH_RECEIVE_TIMEOUT,
TypeError: __init__() got an unexpected keyword argument 'receive_timeout'`

**Comment by JAusm** [comment]
This was a lib issue. closing.
