### ISSUE TITLE
error in settings.LDAP_AUTH_USER_LOOKUP_FIELDS AttributeError: 'NoneType' object has no attribute 'pop'

### ISSUE THREAD

**Issue by imatsu** [etianen/django-python3-ldap#144]
Synchronizing an active windows directory, this error is generated.

```
LDAP connect succeeded
{'first_name': 'Admin', 'last_name': 'Admin', 'email': 'adm@adm.com'}
'username'
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 24, in handle
    for user in connection.iter_users():
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 96, in <genexpr>
    if entry["type"] == "searchResEntry"
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 62, in _get_or_create_user
    in settings.LDAP_AUTH_USER_LOOKUP_FIELDS
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 61, in <dictcomp>
    for field_name
AttributeError: 'NoneType' object has no attribute 'pop'
```

**Comment by etianen** [comment]
Are you using a custom LDAP_AUTH_CLEAN_USER_DATA function? It looks like
it's returning None.

**Comment by imatsu** [comment]
My settings.py:

```python
# LDAP
LDAP_AUTH_URL = config.get('LDAP', 'LDAP_AUTH_URL')
LDAP_AUTH_USE_TLS = config.getboolean('LDAP', 'LDAP_AUTH_USE_TLS')
LDAP_AUTH_SEARCH_BASE = config.get('LDAP', 'LDAP_AUTH_SEARCH_BASE')
LDAP_AUTH_OBJECT_CLASS = config.get('LDAP', 'LDAP_AUTH_OBJECT_CLASS')
LDAP_AUTH_USER_LOOKUP_FIELDS = ('username',)
LDAP_AUTH_FORMAT_USERNAME = 'django_python3_ldap.utils.format_username_active_directory_principal'
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = config.get('LDAP', 'LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN')
LDAP_AUTH_CLEAN_USER_DATA = 'libraries.utils.clean_user_data'
LDAP_AUTH_CONNECTION_USERNAME = config.get('LDAP', 'LDAP_AUTH_CONNECTION_USERNAME')
LDAP_AUTH_CONNECTION_PASSWORD = config.get('LDAP', 'LDAP_AUTH_CONNECTION_PASSWORD')

LDAP_AUTH_USER_FIELDS = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
    'is_active': 'userAccountControl',
}
```

My function
```python
model_data = clean_user_data_base(ldap_data)
username = ldap_data['username'][:3]

if username.lower() == 'adm':
    model_data['is_staff'] = True
    model_data['is_superuser'] = True

try:
    model_data['first_name'] = ldap_data['first_name']
except KeyError:
    model_data['first_name'] = ldap_data['username']

try:
    model_data['last_name'] = ldap_data['last_name']
except KeyError:
    model_data['last_name'] = 'Sisap'

enabled_values = ['512', '544', '66048', '66080']
try:
    if model_data['is_active'] in enabled_values:
        model_data['is_active'] = True
    else:
        model_data['is_active'] = False
except KeyError:
    model_data['is_active'] = False

try:
    model_data['email'] = ldap_data['email']
except KeyError:
    model_data['email'] = '{}@{}'.format(ldap_data['username'], 'sisap.com')

return model_data
```

**Comment by imatsu** [comment]
It is not a user, it is a contact for that reason it does not have a property sAMAccountName.

Testing with a new code I could realize the username, sorry

**Comment by etianen** [comment]
No worries! Glad you found a solution!
