### ISSUE TITLE
LDAP_AUTH_FORMAT_SEARCH_FILTERS: ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter

### ISSUE THREAD

**Issue by imatsu** [etianen/django-python3-ldap#151]
I'm trying to synchronize some data by adding the following search parameter:

```python
def custom_format_search_filters(ldap_fields):
    search_filters = format_search_filters(ldap_fields)
    search_filters.append('(&(objectClass=user)(primaryGroupID=513)!(isCriticalSystemObject=TRUE))')
    return search_filters
```

Error:

['(objectClass=person)', '(&(primaryGroupID=513)!(isCriticalSystemObject=TRUE))']
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 24, in handle
    for user in connection.iter_users():
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 93, in <genexpr>
    self._get_or_create_user(entry)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 64, in paged_search_generator
    None if cookie is True else cookie)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/ldap3/core/connection.py", line 776, in search
    check_names=self.check_names)
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/ldap3/operation/search.py", line 372, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/home/hlozada/.local/share/virtualenvs/sisap-backend-tZXLRNUd/lib/python3.6/site-packages/ldap3/operation/search.py", line 215, in parse_filter
    raise LDAPInvalidFilterError('malformed filter')
ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter

Note:
Without the isCriticalSystemObject parameter it works

**Comment by klainn** [comment]
If you haven't already, try something like this:

`search_filters.append('(&(objectClass=user)(primaryGroupID=513)(!(isCriticalSystemObject=TRUE)))')`

Wrapped an extra set of () around the not-filtered clause. I believe that has to be done.
