### ISSUE TITLE
How to run unit tests locally

### ISSUE THREAD

**Issue by dirksen** [etianen/django-python3-ldap#168]
I tried to run unit tests locally by following .travis.yml, but to no avail. Here're my steps:
```
$ pip install flake8 coverage django==2.0
$ coverage run tests/manage.py test django_python3_ldap
```
It came back with an exception:
```
coverage run tests/manage.py test django_python3_ldap
Traceback (most recent call last):
  File "tests/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dirksen/dev/django-python3-ldap/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/dirksen/dev/django-python3-ldap/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/dirksen/dev/django-python3-ldap/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/dirksen/dev/django-python3-ldap/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/dirksen/dev/django-python3-ldap/venv/lib/python3.7/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests'
```

Any pointer is appreciated!

**Comment by dirksen** [comment]
I have resolved the problem but not sure about the solution. 

The exception above was caused by a misconfiguration: 
```
export DJANGO_SETTINGS_MODULE='tests.django_python3_ldap_test.settings'
```
I was trying to old way of running test: `python setup.py test`, which requires the environment variable to locate the settings.py. But it lead to an error `Apps aren't loaded yet`. Then I noticed `.travis.yml`, so I switched to follow the test steps outlined in `.travis.yml`, but the environment variable DJANGO_SETTINGS_MODULE derailed the test.

After clearing up my environment, the test still failed, complaining unable to find module djano_python3_ldap. It turns out the working directory has dropped down to `./django-python3-ldap/tests/`. I got over it by add the parent `./django-python3-ldap/` to sys.path.
