### ISSUE TITLE
Exclude imports from settings.py

### ISSUE THREAD

**Issue by mnach** [etianen/django-python3-ldap#17]
Dear, etianen!

I found a strange issue.
In our project there is a two settings files:
* settings.py - test settings for development purposes
* prod_settings.py - production settings

In the top of prod_settings we have an import line
```python
from .settings import *
```
This code is failed because of necessity to import functions from this application:
```python
LDAP_AUTH_CLEAN_USER_DATA = django_python3_ldap.utils.clean_user_data
import django_python3_ldap.utils
```
Traceback at the end of this letter.

So, I want to ask you: can we get rid of those imports?
For example we can switch them to import-strings. Something like this:
```python
# settings.py
LDAP_AUTH_CLEAN_USER_DATA = 'django_python3_ldap.utils.clean_user_data'

# ldap.py _get_or_create_user
from django.utils.module_loading import import_string
user_fields = import_string(settings.LDAP_AUTH_CLEAN_USER_DATA)
```
I will be glad to do that, if you ask me to.
Thanks!

Traceback example
```
Traceback (most recent call last):
  File "/home/mnach/src/internal/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/python/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 14, in <module>
    from django.db.migrations.executor import MigrationExecutor
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/migrations/executor.py", line 6, in <module>
    from .loader import MigrationLoader
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/migrations/loader.py", line 10, in <module>
    from django.db.migrations.recorder import MigrationRecorder
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 9, in <module>
    class MigrationRecorder(object):
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 23, in MigrationRecorder
    class Migration(models.Model):
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 24, in Migration
    app = models.CharField(max_length=255)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 1081, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 161, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/python/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mnach/src/internal/internal/prod_settings.py", line 4, in <module>
    from .settings import *
  File "/home/mnach/src/internal/internal/settings.py", line 221, in <module>
    import django_python3_ldap.utils
  File "/home/mnach/src/internal/django_python3_ldap/utils.py", line 12, in <module>
    from django.contrib.auth.hashers import make_password
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mnach/src/internal/env-3.4.3/lib/python3.4/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.```

**Comment by etianen** [comment]
Hmm... there's no need to import the function if you're using the default
value. But still, this does appear to be a problem.

I like your idea of using a string for specifying the function name.
Ideally, we'd keep backwards-compatibilty with specifying a function object
too. So a function in django_python3_ldap.utils called import_func that
will take either a function object or a string, converting the string to a
function object, and returning it, would seem appropriate.

I'd definitely take a pull request for this.

**Comment by mnach** [comment]
Something like this?
https://github.com/mnach/django-python3-ldap/commit/33e9711058bd40da1df02d125f0d85306bb0a77a

**Comment by etianen** [comment]
That's perfect! Hit me with that pull request!

I remembered about this issue last night, and was going to do a patch myself today. Thanks for beating me to it! :)

**Comment by mnach** [comment]
No problem! I'm glad to do some contribution..
