### ISSUE TITLE
Problem with object or socket (i think)

### ISSUE THREAD

**Issue by 1interceptor3** [etianen/django-python3-ldap#184]
`LDAP connect succeeded
LDAP bind failed: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=XXX,DC=xxx-xxx,DC=ru - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'DC=XXX,DC=xxx-xxx,DC=ru'
  - searchResDone - None
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\ldap.py", line 182, in connection
    yield Connection(c)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\ldap.py", line 206, in authenticate
    return c.get_user(**kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\ldap.py", line 107, in get_user
    if self._connection.search(
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\core\connection.py", line 819, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\strategy\sync.py", line 139, in post_send_search
    responses, result = self.get_response(message_id)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\strategy\base.py", line 401, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=XXX,DC=xxx-xxx,DC=ru - 0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:
	'DC=XXX,DC=xxx-xxx,DC=ru'
  - searchResDone - None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\views\decorators\debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\contrib\auth\views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\views\generic\edit.py", line 141, in post
    if form.is_valid():
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\forms\forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\forms\forms.py", line 175, in errors
    self.full_clean()
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\forms\forms.py", line 377, in full_clean
    self._clean_form()
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\forms\forms.py", line 404, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\contrib\auth\forms.py", line 214, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django\contrib\auth\__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\auth.py", line 23, in authenticate
    return ldap.authenticate(*args, **kwargs)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\ldap.py", line 206, in authenticate
    return c.get_user(**kwargs)
  File "C:\Users\volkov_is\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 162, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
[22/May/2020 14:13:27] "POST /users/login/ HTTP/1.1" 500 187489
Exception ignored in: <generator object connection at 0x0000026355CD50B0>
Traceback (most recent call last):
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\django_python3_ldap\ldap.py", line 187, in connection
    c.unbind()
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\core\connection.py", line 721, in unbind
    self.send('unbindRequest', request, controls)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\strategy\base.py", line 329, in send
    self.sending(ldap_message)
  File "C:\Users\volkov_is\PycharmProjects\sskProject\venv\lib\site-packages\ldap3\strategy\base.py", line 869, in sending
    raise communication_exception_factory(LDAPSocketSendError, type(e)(str(e)))(self.connection.last_error)
ldap3.core.exceptions.LDAPSocketSendError: socket sending error[WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом`

**Comment by etianen** [comment]
I would not expect unbind() to raise an exception. I don't know what would
cause that, I'm afraid.
