### ISSUE TITLE
Problem using ldap_sycn_users

### ISSUE THREAD

**Issue by markgrimes62** [etianen/django-python3-ldap#230]
python manage.py ldap_sync_users

I can login and it will create my user in admin, but i was wanting to sync users so i could apply permissions ahead of time. When i try to run i get error:
LDAP connect succeeded
LDAP bind failed: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=OSL,DC=midwestexp,DC=com - 0000208D: NameErr: DSID-03152973, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=OSL,DC=midwestexp,DC=com'
 - searchResDone - None
Traceback (most recent call last):
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 194, in connection
    yield Connection(c)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 24, in handle
    for user in connection.iter_users():
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 105, in <genexpr>
    self._get_or_create_user(entry)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 68, in paged_search_generator
    None if cookie is True else cookie)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/ldap3/core/connection.py", line 853, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/ldap3/strategy/sync.py", line 178, in post_send_search
    responses, result = self.get_response(message_id)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/ldap3/strategy/base.py", line 403, in get_response
    raise LDAPOperationResult(result=result['result'], description=result['description'], dn=result['dn'], message=result['message'], response_type=result['type'])
ldap3.core.exceptions.LDAPNoSuchObjectResult: LDAPNoSuchObjectResult - 32 - noSuchObject - DC=OSL,DC=midwestexp,DC=com - 0000208D: NameErr: DSID-03152973, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=OSL,DC=midwestexp,DC=com'
 - searchResDone - None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/QOpenSys/pkgs/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/OSLIASPDVP/websites/ldap3/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 27, in handle
    user=user,
  File "/QOpenSys/pkgs/lib/python3.6/contextlib.py", line 126, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()

**Comment by MaykCheck** [comment]
which files should I add in the project file
