### ISSUE TITLE
Settings to connect to anonymous server

### ISSUE THREAD

**Issue by shanemgrey** [etianen/django-python3-ldap#36]
I've tried following the readme here, but can't seem to find the correct settings to make a connection to a test server that has anon access.  

Is this supported?  If so, what settings would be required?

http://drupal.gatech.edu/handbook/public-ldap-server

**Comment by etianen** [comment]
By default, unless you provide settings for LDAP_AUTH_CONNECTION_USERNAME
and LDAP_AUTH_CONNECTION_PASSWORD, django-python3-ldap will connect in
anonymous mode.

**Comment by shanemgrey** [comment]
Using these settings I get the following error when attempting to ```./manage.py ldap_sync_users```:

```
AUTHENTICATION_BACKENDS = ['django_python3_ldap.auth.LDAPBackend']
LDAP_AUTH_URL = "ldap://whitepages.gatech.edu:389"
LDAP_AUTH_SEARCH_BASE = "dc=whitepages,dc=gatech,dc=edu"
LDAP_AUTH_OBJECT_CLASS = "uid"
```

```  
File "/Users/shanegrey/Documents/Practice/drf/env/lib/python3.5/site-packages/ldap3/operation/bind.py", line 57, in bind_operation
    raise LDAPPasswordIsMandatoryError('password is mandatory in simple bind')
ldap3.core.exceptions.LDAPPasswordIsMandatoryError: password is mandatory in simple bind
```

**Comment by shanemgrey** [comment]
### Steps to reproduce

Install django and django_python3_ldap, then start a projecrt and app.

```
mkdir ldap && cd ldap
virtualenv -p python3 env && source env/bin/activate
pip install django
pip install django-python3-ldap
django-admin.py startproject test_ldap .
cd test_ldap
django-admin.py startapp app
cd ..
```

Edit ldap/test_ldap/settings.py INSTALLED_APPS
```
INSTALLED_APPS = [
    ...
    'django_python3_ldap',
]
```

Add to ldap/test_ldap/settings.py
```
AUTHENTICATION_BACKENDS = ('django_python3_ldap.auth.LDAPBackend',)

LDAP_AUTH_URL = 'ldap://whitepages.gatech.edu:389'
LDAP_AUTH_SEARCH_BASE = 'dc=whitepages,dc=gatech,dc=edu'
```

Run: ```./manage.py ldap_sync_users```

Result:

```
/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 15, in handle_noargs
    with ldap.connection(username=settings.LDAP_AUTH_CONNECTION_USERNAME, password=settings.LDAP_AUTH_CONNECTION_PASSWORD) as connection:
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/django_python3_ldap/ldap.py", line 123, in connection
    with ldap3.Connection(ldap3.Server(settings.LDAP_AUTH_URL), user=username, password=password, auto_bind=auto_bind) as c:
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/ldap3/core/connection.py", line 286, in __init__
    self.bind(read_server_info=True)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/ldap3/core/connection.py", line 468, in bind
    request = bind_operation(self.version, self.authentication, self.user, self.password)
  File "/Users/shanegrey/Documents/Practice/ldap/env/lib/python3.5/site-packages/ldap3/operation/bind.py", line 57, in bind_operation
    raise LDAPPasswordIsMandatoryError('password is mandatory in simple bind')
ldap3.core.exceptions.LDAPPasswordIsMandatoryError: password is mandatory in simple bind
```

From what I can tell, the error is a result of the user being defined somewhere and ldap3 is picking that up and choosing SIMPLE instead of ANONYMOUS.  But I'm not sure how since this is a totally fresh django install without even creating a superuser. 

What am I missing?

**Comment by etianen** [comment]
Hi,

Interestingly, the anonymous LDAP server we use in the office works just
fine, but I can reproduce the bug with your server. I really hate LDAP! :P

Try the latest master branch. It should fix your issue.

**Comment by shanemgrey** [comment]
@etianen Thanks for finding the issue and patching!  

That part seems to work now.  

Unfortunately, lacking deep understanding of the django user auth system, I'm still stuck getting this integrated.  

My goal, and my understanding of the purpose of this project, is to use the LDAP server to authenticate users listed in the directory so I can assign permissions in django without maintaining a distinct auth system from the rest of the company apps. 

While I can connect to a server like ldap.forumsys.com using apache directory studio and see a list of users, and I can run the ldap_sync_users without error now, any attempt to login as a user with the django admin still fails.  

Is there a more complete tutorial you can point me at for all details of a basic auth setup?

**Comment by etianen** [comment]
Users created by django-python3-ldap are created with no privileges  and no is_staff flag, so won't be able to log into the admin system.

You can customize user model creation by overriding the LDAP_AUTH_CLEAN_USER_DATA and LDAP_AUTH_SYNC_USER_RELATIONS settings.

https://github.com/etianen/django-python3-ldap#available-settings

For example:

``` py
# settings.py
LDAP_AUTH_CLEAN_USER_DATA = "your_package.ldap.custom_clean_user_data

# your_package.ldap
from django_python3_ldap.utils import clean_user_data

def custom_clean_user_data(user_data):
    user_data = clean_user_data(user_data)
    user_data.is_staff = True
    return user_data
```
