### ISSUE TITLE
Using LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal" doesnt work

### ISSUE THREAD

**Issue by SRPlatin** [etianen/django-python3-ldap#76]
config snippet:
`LDAP_AUTH_SEARCH_BASE = "ou=Benutzer,dc=test,dc=domain,dc=de"

LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "test.doamin.de"

LDAP_AUTH_CONNECTION_USERNAME = "username"
LDAP_AUTH_CONNECTION_PASSWORD = "password"

LDAP_AUTH_FORMAT_USERNAME = "django_python3_ldap.utils.format_username_active_directory_principal"
LDAP_AUTH_ACTIVE_DIRECTORY_DOMAIN = "test.doamin.de"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}`
crashes with

`Traceback (most recent call last):
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
AttributeError: module 'django_python3_ldap.utils' has no attribute 'format_username_active_directory_principal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django_python3_ldap\management\commands\ldap_sync_users.py", line 17, in handle
    password=settings.LDAP_AUTH_CONNECTION_PASSWORD,
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django_python3_ldap\ldap.py", line 132, in connection
    username = import_func(settings.LDAP_AUTH_FORMAT_USERNAME)(kwargs)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django_python3_ldap\utils.py", line 19, in import_func
    return import_string(func)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\module_loading.py", line 27, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Tobias Liese\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\module_loading.py", line 23, in import_string
    return getattr(module, class_name)
ImportError: Module "django_python3_ldap.utils" does not define a "format_username_active_directory_principal" attribute/class`

when running: `python manage.py ldap_sync_users`

**Comment by etianen** [comment]
Have you upgraded to the latest django-python3-ldap?

**Comment by etianen** [comment]
Specifically, to use this feature you need to use the master branch.

**Comment by SRPlatin** [comment]
oh ok not I did use the version from pypy

**Comment by vdksystem** [comment]
Could you update pypy, beause it's easyer to use for deployment?

**Comment by etianen** [comment]
0.10.0 is now out.
