### ISSUE TITLE
Problem with ldap_sync_users command (need ldap3 v2.2.3 module)

### ISSUE THREAD

**Issue by tazou** [etianen/django-python3-ldap#78]
Hello,
Thanks for your clear documentation :) 
I try to make working your module for the first time but I have some issue.

My LDAP server is particular and need the last stable version (2.2.3) of ldap3 python module.
You can see the issue corrected 2 days ago here : https://github.com/cannatag/ldap3/issues/334

When I try to import ldap users in django with your module, it's not working.

**You can see my try here :** 
```
gduale:~:$ . ./py361-test/bin/activate
(py361-test) gduale:~:$ pip install django-python3-ldap
Collecting django-python3-ldap
  Using cached django-python3-ldap-0.9.14.tar.gz
Collecting django>=1.8 (from django-python3-ldap)
  Using cached Django-1.11-py2.py3-none-any.whl
Collecting ldap3==2.2.0 (from django-python3-ldap)
  Using cached ldap3-2.2.0-py2.py3-none-any.whl
Collecting pytz (from django>=1.8->django-python3-ldap)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting pyasn1>=0.1.8 (from ldap3==2.2.0->django-python3-ldap)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Installing collected packages: pytz, django, pyasn1, ldap3, django-python3-ldap
  Running setup.py install for django-python3-ldap ... done
Successfully installed django-1.11 django-python3-ldap-0.9.14 ldap3-2.2.0 pyasn1-0.2.3 pytz-2017.2
```

**Then I know that with ldap3 version 2.2.0 it will not work (I already try), so I install the latest version :** 
```
(py361-test) gduale:~:$ pip install --upgrade ldap3
Collecting ldap3
  Using cached ldap3-2.2.3-py2.py3-none-any.whl
Requirement already up-to-date: pyasn1>=0.1.8 in ./py361-test/lib/python3.6/site-packages (from ldap3)
Installing collected packages: ldap3
  Found existing installation: ldap3 2.2.0
    Uninstalling ldap3-2.2.0:
      Successfully uninstalled ldap3-2.2.0
Successfully installed ldap3-2.2.3
```

**Then I try to sync the users, but it fails :** 
```
(py361-test) gduale:~/django-projects/test-c2i/c2i:$ python manage.py ldap_sync_users
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/gduale/make_python/python-3.6.1/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django_python3_ldap/management/commands/ldap_sync_users.py", line 21, in handle
    for user in connection.iter_users():
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 90, in <genexpr>
    if entry["type"] == "searchResEntry"
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django_python3_ldap/ldap.py", line 66, in _get_or_create_user
    **user_lookup
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/db/models/query.py", line 475, in update_or_create
    lookup, params = self._extract_model_params(defaults, **kwargs)
  File "/home/gduale/py361-test/lib/python3.6/site-packages/django/db/models/query.py", line 531, in _extract_model_params
    "', '".join(sorted(invalid_params)),
django.core.exceptions.FieldError: Invalid field name(s) for model User: 'd', 'i', 'u'.
```

Do you know if is it possible to make working your module with the latest stable version of ldap3 please ?
Thank you,
Best regards.

**Comment by etianen** [comment]
I've just pushed a version to master that works with ldap3==2.2.3

However, I think your issue is due to misconfiguration. Can you let me see
your settings.py?

**Comment by tazou** [comment]
Hi Dave,
Thanks for your commit.
I try with the latest version, and it use ldap3 v2.2.3 but the problem is the same.
You are right, it's maybe a configuration problem.
You can find here my settings.py : 
[settings.py.zip](https://github.com/etianen/django-python3-ldap/files/972910/settings.py.zip)

Best regards.

**Comment by etianen** [comment]
LDAP_AUTH_USER_LOOKUP_FIELDS = ("uid")

should be:

LDAP_AUTH_USER_LOOKUP_FIELDS = ("uid",)

Then it should work :)

**Comment by tazou** [comment]
Hi Dave,
Thanks for your help :) 

I try with your modification, and now I have this error : 
```
(py361-django-ldap) gduale:~/django-projects/test-c2i/c2i:$ python manage.py ldap_sync_users
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/gduale/make_python/python-3.6.1/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/django_python3_ldap-0.9.14-py3.6.egg/django_python3_ldap/management/commands/ldap_sync_users.py", line 21, in handle
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/django_python3_ldap-0.9.14-py3.6.egg/django_python3_ldap/ldap.py", line 90, in <genexpr>
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/django_python3_ldap-0.9.14-py3.6.egg/django_python3_ldap/ldap.py", line 66, in _get_or_create_user
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/db/models/query.py", line 475, in update_or_create
    lookup, params = self._extract_model_params(defaults, **kwargs)
  File "/home/gduale/py361-django-ldap/lib/python3.6/site-packages/Django-1.11-py3.6.egg/django/db/models/query.py", line 531, in _extract_model_params
    "', '".join(sorted(invalid_params)),
django.core.exceptions.FieldError: Invalid field name(s) for model User: 'uid'.
```
Do you have an idea about it please ?
Best regards.

**Comment by tazou** [comment]
Hi,
Sorry my fault...
I change this parameter with : 
LDAP_AUTH_USER_LOOKUP_FIELDS = ("username",)

And now the synchronization is working !

Thank a lot again for all your help !

**Comment by etianen** [comment]
Excellent! LDAP is needlessly hard!

**Comment by tazou** [comment]
Now I have authentication problem.
Can we discuss about it here please ?

**Comment by etianen** [comment]
Sure.

**Comment by tazou** [comment]
Ok thank you :) 

I can't login with my LDAP credentials.

I put this logging information in settings.py : 
```
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django_python3_ldap": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}
```
And when I try to ldap_sync_users it works fine, but when I try to authenticate, it fails.
On console I have not a lot of information.
When I try to log with local 'admin' account, I have this : 
LDAP connect failed: LDAPNoSuchObjectResult - 32 - noSuchObject - ou=utilisateurs,o=vdm - None - bindResponse - None 
And it's logical in my opinion.

And when I try to login with 'gduale' ldap account, I see nothing interresting in console : 
```
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/May/2017 10:11:13] "GET / HTTP/1.1" 200 1716
[03/May/2017 10:11:16] "GET /admin HTTP/1.1" 301 0
[03/May/2017 10:11:16] "GET /admin/ HTTP/1.1" 302 0
[03/May/2017 10:11:17] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
[03/May/2017 10:11:17] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[03/May/2017 10:11:17] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[03/May/2017 10:11:17] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[03/May/2017 10:11:17] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[03/May/2017 10:11:17] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[03/May/2017 10:11:22] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1812
[03/May/2017 10:11:22] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
```

Maybe the password column is not in the right format in the database ? Do you check the password column or just query LDAP ?
You can see the database entry for my account : 
![capture du 2017-05-03 12-13-34](https://cloud.githubusercontent.com/assets/6482957/25656611/23dea126-2ffa-11e7-8320-e4a82b423ae4.png)

Thank you !

**Comment by etianen** [comment]
I've just pushed a commit to master that increases the logging verbosity.
Could you install the latest from master and let me know what your console
says during the failed gduale login?

**Comment by tazou** [comment]
Hi,
I try with your code up-to-date, and I have this log : 
```
(py361-django-ldap) gduale:~/django-projects/test-c2i/c2i:$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
May 03, 2017 - 11:55:45
Django version 1.11, using settings 'c2i.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/May/2017 11:55:50] "GET / HTTP/1.1" 200 1716
[03/May/2017 11:55:53] "GET /admin/ HTTP/1.1" 302 0
[03/May/2017 11:55:54] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
[03/May/2017 11:55:54] "GET /static/admin/css/login.css HTTP/1.1" 304 0
[03/May/2017 11:55:54] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/May/2017 11:55:54] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
LDAP connect succeeded
LDAP user lookup succeeded
[03/May/2017 11:56:02] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1812
```

For information, the login fail.

Regards.

**Comment by etianen** [comment]
Hmm. It looks like that user's "is_staff" flag is set to false, which is
preventing login to the admin site.

Change that flag to true, and you should be able to log in.

**Comment by tazou** [comment]
Hi,
Oh yes it's working with this flag ! I can login :) 

And if I put : 
AUTHENTICATION_BACKENDS = {"django_python3_ldap.auth.LDAPBackend",'django.contrib.auth.backends.ModelBackend',}

I can login with local user and ldap user ! It's perfect :) 

Is it possible to give the flag "is_staff" to an ldap user by default ? (If he login successfully of course).

Thank you.
Regards.

**Comment by etianen** [comment]
You can provide your own implementation of LDAP_AUTH_CLEAN_USER_DATA for
this purpose. Check out the docs here:
https://github.com/etianen/django-python3-ldap#available-settings

You'll want something like this:

https://gist.github.com/etianen/1d5d98e2441c26d11e7bdba3e9a3a17c

**Comment by tazou** [comment]
Hi Dave,
Thanks a lot for all your help ! :) 
My original problem was to execute with success the "ldap_sync_users" command, and now it's working.
So I close this bug.
I just sent you an Amazon gift card to thank you :) 
Best regards.

**Comment by etianen** [comment]
Hey, no worries, and thanks for the gift card! Always a pleasure to help
out a fellow coder!
