### ISSUE TITLE
'DatabaseWrapper' object has no attribute 'queries_log'

### ISSUE THREAD

**Issue by msonsona** [etianen/django-python3-ldap#90]
I've followed installation steps 1-4. 
Now if I go to http://0.0.0.0:8000/ to try to test the login against the LDAP I get this error in the console:

```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
     self.result = application(self.environ, self.start_response)
   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
     return self.application(environ, start_response)
   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 155, in __call__
     signals.request_started.send(sender=self.__class__, environ=environ)
   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
     for receiver in self._live_receivers(sender)
   File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
     for receiver in self._live_receivers(sender)
   File "/usr/local/lib/python3.6/site-packages/django/db/__init__.py", line 54, in reset_queries
     conn.queries_log.clear()
 AttributeError: 'DatabaseWrapper' object has no attribute 'queries_log'

```
Any idea?

From `pip freeze`:
```
Django==1.11
django-python3-ldap==0.10.0
ldap3==2.2.3
```
Any additional info I could provide to help diagnose the issue?
Thanks!

**Comment by etianen** [comment]
Are you certain that this is due to django-python3-ldap?

None of those lines in the traceback touch the django-python3-ldap
codebase, or any of it's dependencies. At a guess, I'd say something
appears to be wrong with the staticfiles setup.

**Comment by msonsona** [comment]
Hi, thanks @etianen for your feedback.
Already worked out something small with a coworker using ldap3.

Keep it up, good job!
